All female line-up blog post
UIKonf/uikonf-website pull request #34
Opened 2019-01-29 22:16 UTC by mietzmithut

Added the blog post. Unfortunately I didn't find where the authors are defined.

2019-01-30 18:28 UTC, basine approved these changes

2019-01-30 18:28 UTC, basine commented on _posts/2019-01-09-all-female-speaker-lineup.md
> +author: basine
ekurutepe ist in der _config.yml zu finden

2019-01-30 18:28 UTC, basine commented on _posts/2019-01-09-all-female-speaker-lineup.md
> +description: All female speaker line-up
das wid für die meta description im html header verwendet. das benutzt google für die vorschau snippets. es macht also sinn, hier was zu schreiben, wie "To support women in tech and diversity in general, UIKonf 2019 will feature an all-female speaker line-up."

2019-01-30 18:28 UTC, basine commented on _posts/2019-01-09-all-female-speaker-lineup.md
> +---
👆🏻url / file-name hat das falsche datum (ist nicht so wichtig, weil der erste buchstabe ein a ist)

2019-01-30 18:30 UTC, basine commented on _posts/2019-01-09-all-female-speaker-lineup.md
> +author: basine
falls du dich selbst mal als author hinzufügen willst, musst du die _config.yml bearbeiten. Wenn du dort änderungen vornimmst, musst du deinen localen server neu starten, um die änderungen zu sehen.

2019-01-30 18:31 UTC, basine requested changes
sorry hab den falschen toggle ausgewählt :D

2019-01-30 18:37 UTC, basine commented on _posts/2019-01-09-all-female-speaker-lineup.md
> +author: basine
hab die steps zum übergabeprotokoll hinzugefügt

2019-01-30 18:57 UTC, mietzmithut commented on _posts/2019-01-09-all-female-speaker-lineup.md
> +author: basine
merci :)

2019-01-30 19:15 UTC, basine approved these changes

2019-01-31 09:22 UTC, ekurutepe approved these changes

2019-01-31 09:22 UTC, merged